---
- name: "jongmin-server 인프라 구성 적용"
  hosts: homeserver
  become: true
  roles:
    - common
    - cpu_power_management
    - role: docker
      tags:
        - docker
    - traefik
    - ddns
    - fail2ban
    - homepage
    - tailscale
    - monitoring
