---
- hosts: homeserver
  become: true
  vars_files:
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/all_vault.yml
  roles:
    - common
    - cpu_power_management
    - docker
    - traefik
    - ddns
    - fail2ban
    - homepage
    - tailscale
